version: '3.8'

services:
  # Web前端构建服务
  web:
    build:
      context: ./web
    container_name: xhs2ai-web-builder
    volumes:
      - ./web:/app
      - web_build:/app/out
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost/api
    command: sh -c "npm ci && npm run build && echo '静态文件已生成' && tail -f /dev/null"
    networks:
      - xhs2ai-network

  # Backend server service
  server:
    build:
      context: ./server
    container_name: xhs2ai-server
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - ./server/.env:/app/.env
      - server_outputs:/app/outputs
      - server_templates:/app/templates
      - server_images:/app/generated_images
      - server_videos:/app/minimaxi_videos
      - server_videos2:/app/videos
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - PYTHONPATH=/app
    networks:
      - xhs2ai-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: xhs2ai-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - server_outputs:/usr/share/nginx/html/outputs
      - server_templates:/usr/share/nginx/html/templates
      - web_build:/usr/share/nginx/html  # 使用共享卷挂载静态文件
    depends_on:
      - web
      - server
    networks:
      - xhs2ai-network

networks:
  xhs2ai-network:
    driver: bridge

volumes:
  server_outputs:
  server_templates:
  server_images:
  server_videos:
  server_videos2:
  web_build:  # 新增共享卷，用于web和nginx之间共享构建结果 