version: '3.8'

services:
  # Web frontend service (Production mode)
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: xhs2ai-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
    expose:
      - "3000"
    networks:
      - xhs2ai-network

  # Backend server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: xhs2ai-server
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - ./server/src:/app/src
      - ./server/.env:/app/.env
      - server_outputs:/app/outputs
      - server_templates:/app/templates
      - server_images:/app/generated_images
      - server_videos:/app/minimaxi_videos
      - server_videos2:/app/videos
      - server_magazine_cards:/app/magazine_cards
      - server_uploads:/app/uploads
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - PYTHONPATH=/app
      - BASE_URL=/
    networks:
      - xhs2ai-network

  # Nginx service - 唯一对外暴露的服务
  nginx:
    image: nginx:alpine
    container_name: xhs2ai-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - server_outputs:/usr/share/nginx/html/outputs
      - server_templates:/usr/share/nginx/html/templates
      - server_magazine_cards:/usr/share/nginx/html/magazine_cards
      - server_uploads:/usr/share/nginx/html/uploads
    depends_on:
      - server
      - web
    networks:
      - xhs2ai-network

networks:
  xhs2ai-network:
    driver: bridge

volumes:
  server_outputs:
  server_templates:
  server_images:
  server_videos:
  server_videos2:
  server_magazine_cards:
  server_uploads: 