version: '3.8'

services:
  # Web frontend service
  web:
    build:
      context: ./web
    container_name: xhs2ai-web
    restart: unless-stopped
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
      - ./web/public:/app/public
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost/api
    depends_on:
      - server
    networks:
      - xhs2ai-network

  # Backend server service
  server:
    build:
      context: ./server
    container_name: xhs2ai-server
    restart: unless-stopped
    volumes:
      - ./server:/app
      - server_outputs:/app/outputs
      - server_templates:/app/templates
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
    networks:
      - xhs2ai-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: xhs2ai-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - server_outputs:/usr/share/nginx/html/outputs
      - server_templates:/usr/share/nginx/html/templates
    depends_on:
      - web
      - server
    networks:
      - xhs2ai-network

networks:
  xhs2ai-network:
    driver: bridge

volumes:
  server_outputs:
  server_templates: 