version: '3.8'

services:
  # Backend server service
  server:
    build:
      context: ./server
    container_name: xhs2ai-server
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - ./server/.env:/app/.env
      - server_outputs:/app/outputs
      - server_templates:/app/templates
      - server_images:/app/generated_images
      - server_videos:/app/minimaxi_videos
      - server_videos2:/app/videos
    environment:
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_BASE_URL=${LLM_BASE_URL}
      - PYTHONPATH=/app
    networks:
      - xhs2ai-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: xhs2ai-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - server_outputs:/usr/share/nginx/html/outputs
      - server_templates:/usr/share/nginx/html/templates
      - ./web/out:/usr/share/nginx/html  # 直接挂载静态编译后的文件
    depends_on:
      - server
    networks:
      - xhs2ai-network

networks:
  xhs2ai-network:
    driver: bridge

volumes:
  server_outputs:
  server_templates:
  server_images:
  server_videos:
  server_videos2: 